/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hydrationtracker;

/*
* HydrationTrackerGUI.java
* @author: Stefany Rachor Junges
* 09/11/2024
*/

public class HydrationTrackerGUI extends javax.swing.JFrame {
    
    public HydrationTrackerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whiteJPANEL = new javax.swing.JPanel();
        iconLBL = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        subtitleLBL = new javax.swing.JLabel();
        hcDescriptionTA = new javax.swing.JTextArea();
        hgDescriptionTA = new javax.swing.JTextArea();
        lineSPRT = new javax.swing.JSeparator();
        hydrocheckBTN = new javax.swing.JButton();
        hydroguideBTN = new javax.swing.JButton();
        waterbottleLBL = new javax.swing.JLabel();
        dropletLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        whiteJPANEL.setBackground(new java.awt.Color(255, 255, 255));

        iconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hydrationtracker/splash.png"))); // NOI18N

        titleLBL.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(0, 153, 255));
        titleLBL.setText("Hydration Tracker");

        subtitleLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        subtitleLBL.setForeground(new java.awt.Color(102, 204, 255));
        subtitleLBL.setText("Your first step to stay hidrated.");

        hcDescriptionTA.setEditable(false);
        hcDescriptionTA.setBackground(new java.awt.Color(233, 248, 255));
        hcDescriptionTA.setColumns(20);
        hcDescriptionTA.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        hcDescriptionTA.setForeground(new java.awt.Color(51, 204, 255));
        hcDescriptionTA.setRows(5);
        hcDescriptionTA.setText("\nMonitor and improve your hydration habits by keeping track of\nyour water intake for at least three days and find out your\naverage intake + your monthly and yearly projection, while also\nreceiving feedback.");
        hcDescriptionTA.setMargin(new java.awt.Insets(2, 10, 2, 6));

        hgDescriptionTA.setEditable(false);
        hgDescriptionTA.setBackground(new java.awt.Color(233, 248, 255));
        hgDescriptionTA.setColumns(20);
        hgDescriptionTA.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        hgDescriptionTA.setForeground(new java.awt.Color(51, 204, 255));
        hgDescriptionTA.setRows(5);
        hgDescriptionTA.setText("\nCalculate a recommended daily water intake tailored just for\nyou based on age, weight, exercise level and climate type!");
        hgDescriptionTA.setMargin(new java.awt.Insets(2, 10, 2, 6));

        lineSPRT.setForeground(new java.awt.Color(51, 153, 255));

        hydrocheckBTN.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        hydrocheckBTN.setForeground(new java.awt.Color(0, 153, 255));
        hydrocheckBTN.setText("HydroCheck");
        hydrocheckBTN.setBorderPainted(false);
        hydrocheckBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hydrocheckBTNActionPerformed(evt);
            }
        });

        hydroguideBTN.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        hydroguideBTN.setForeground(new java.awt.Color(0, 153, 255));
        hydroguideBTN.setText("HydroGuide");
        hydroguideBTN.setBorderPainted(false);
        hydroguideBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hydroguideBTNActionPerformed(evt);
            }
        });

        waterbottleLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hydrationtracker/waterbottleicon.png"))); // NOI18N
        waterbottleLBL.setText("jLabel1");

        dropletLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hydrationtracker/dropleticon.png"))); // NOI18N
        dropletLBL.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hydrationtracker/handicon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jButton1.setForeground(new java.awt.Color(51, 204, 255));
        jButton1.setText("<< back to main app");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout whiteJPANELLayout = new javax.swing.GroupLayout(whiteJPANEL);
        whiteJPANEL.setLayout(whiteJPANELLayout);
        whiteJPANELLayout.setHorizontalGroup(
            whiteJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whiteJPANELLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(whiteJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(whiteJPANELLayout.createSequentialGroup()
                        .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(whiteJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(subtitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lineSPRT, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(iconLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whiteJPANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(whiteJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waterbottleLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropletLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whiteJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(hydroguideBTN)
                    .addComponent(hydrocheckBTN)
                    .addComponent(hcDescriptionTA, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hgDescriptionTA, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        whiteJPANELLayout.setVerticalGroup(
            whiteJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whiteJPANELLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(whiteJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLBL)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSPRT, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(hydrocheckBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whiteJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hcDescriptionTA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(whiteJPANELLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(waterbottleLBL)))
                .addGroup(whiteJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(whiteJPANELLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hydroguideBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hgDescriptionTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(whiteJPANELLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(dropletLBL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(iconLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whiteJPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 435, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whiteJPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hydroguideBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hydroguideBTNActionPerformed
        //Creating a new instance of HydrationGoalGUI
        HydrationGoalGUI hgui = new HydrationGoalGUI();
        //Opening HydrationGoalGUI
        hgui.setVisible(true);
        //Closing current window
        dispose();
    }//GEN-LAST:event_hydroguideBTNActionPerformed

    private void hydrocheckBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hydrocheckBTNActionPerformed
        //Creating a new instance of AverageGUI
        AverageGUI avgui = new AverageGUI();
        //Opening AverageGUI
        avgui.setVisible(true);
        //Closing current window
        dispose();       
    }//GEN-LAST:event_hydrocheckBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Creating a new instance of MainAppGUI
        MainAppGUI mainGui = new MainAppGUI();
        //Opening MainAppGUI
        mainGui.setVisible(true);
        //Closing current window
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HydrationTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HydrationTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HydrationTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HydrationTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HydrationTrackerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dropletLBL;
    private javax.swing.JTextArea hcDescriptionTA;
    private javax.swing.JTextArea hgDescriptionTA;
    private javax.swing.JButton hydrocheckBTN;
    private javax.swing.JButton hydroguideBTN;
    private javax.swing.JLabel iconLBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator lineSPRT;
    private javax.swing.JLabel subtitleLBL;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel waterbottleLBL;
    private javax.swing.JPanel whiteJPANEL;
    // End of variables declaration//GEN-END:variables

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
