/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sleeptrackerapp;

/**
 *
 * @author muril
 */
public class IdealBedTimeGUI extends javax.swing.JFrame {

    /**
     * Creates new form IdealBedTimeGUI
     */
    public IdealBedTimeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        idealbedtimeLBL = new javax.swing.JLabel();
        ibttext1LBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ibttext2LBL = new javax.swing.JLabel();
        ibtquestionLBL = new javax.swing.JLabel();
        ibtquestionTF = new javax.swing.JTextField();
        ibtmaleRB = new javax.swing.JRadioButton();
        ibtfemaleRB = new javax.swing.JRadioButton();
        ibtgender = new javax.swing.JLabel();
        ibtreturnBTN = new javax.swing.JButton();
        ibtmainpageBTN = new javax.swing.JButton();
        ibtcalculateBTN = new javax.swing.JButton();
        ibtageLBL = new javax.swing.JLabel();
        ibtTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 167, 186));

        idealbedtimeLBL.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        idealbedtimeLBL.setText("Ideal Bed Time");

        ibttext1LBL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ibttext1LBL.setText("According to your age and gender, you require a different amount of sleep.");

        ibttext2LBL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ibttext2LBL.setText("Check what time is your ideal time to go to bed to have a good night of sleep. ");

        ibtquestionLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtquestionLBL.setText("What time do you need to wake up?");

        ibtmaleRB.setBackground(new java.awt.Color(186, 167, 186));
        buttonGroup1.add(ibtmaleRB);
        ibtmaleRB.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtmaleRB.setText("Male");

        ibtfemaleRB.setBackground(new java.awt.Color(186, 167, 186));
        buttonGroup1.add(ibtfemaleRB);
        ibtfemaleRB.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtfemaleRB.setText("Female");

        ibtgender.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtgender.setText("Gender:");

        ibtreturnBTN.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtreturnBTN.setText("RETURN TO SLEEP TRACKER PAGE");
        ibtreturnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibtreturnBTNActionPerformed(evt);
            }
        });

        ibtmainpageBTN.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtmainpageBTN.setText("RETURN  TO MAIN PAGE");

        ibtcalculateBTN.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        ibtcalculateBTN.setText("CALCULATE!");

        ibtageLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtageLBL.setText("Age:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ibttext2LBL, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(idealbedtimeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ibtquestionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ibtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(115, 115, 115))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(ibtquestionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ibtfemaleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ibtmaleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addComponent(ibtTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addComponent(ibtageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ibtcalculateBTN)
                            .addGap(92, 92, 92))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ibttext1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(ibtreturnBTN)
                                    .addGap(59, 59, 59)
                                    .addComponent(ibtmainpageBTN)))
                            .addGap(61, 61, 61)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(idealbedtimeLBL)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ibttext1LBL)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ibttext2LBL)
                    .addGap(12, 12, 12)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ibtquestionLBL)
                        .addComponent(ibtgender))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ibtquestionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ibtmaleRB)
                            .addComponent(ibtfemaleRB)))
                    .addGap(18, 18, 18)
                    .addComponent(ibtageLBL)
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ibtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ibtcalculateBTN))
                    .addGap(18, 36, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ibtreturnBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ibtmainpageBTN))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ibtreturnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibtreturnBTNActionPerformed
        // TODO add your handling code here:
        SleepTrackerMainPageGUI stmp = new SleepTrackerMainPageGUI();
        stmp.setVisible(true);
        dispose();
    }//GEN-LAST:event_ibtreturnBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdealBedTimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdealBedTimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdealBedTimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdealBedTimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdealBedTimeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField ibtTF;
    private javax.swing.JLabel ibtageLBL;
    private javax.swing.JButton ibtcalculateBTN;
    private javax.swing.JRadioButton ibtfemaleRB;
    private javax.swing.JLabel ibtgender;
    private javax.swing.JButton ibtmainpageBTN;
    private javax.swing.JRadioButton ibtmaleRB;
    private javax.swing.JLabel ibtquestionLBL;
    private javax.swing.JTextField ibtquestionTF;
    private javax.swing.JButton ibtreturnBTN;
    private javax.swing.JLabel ibttext1LBL;
    private javax.swing.JLabel ibttext2LBL;
    private javax.swing.JLabel idealbedtimeLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
