/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sleeptrackerapp;

/**
 *
 * @author muril
 */
public class SleepCalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form SleepCalculatorGUI
     */
    public SleepCalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sundayLBL = new javax.swing.JLabel();
        fridayTF = new javax.swing.JTextField();
        mondayLBL = new javax.swing.JLabel();
        sundayTF = new javax.swing.JTextField();
        mondayTF = new javax.swing.JTextField();
        thursdayLBL = new javax.swing.JLabel();
        wednesdayTF = new javax.swing.JTextField();
        wednesdayLBL = new javax.swing.JLabel();
        tuesdayTF = new javax.swing.JTextField();
        saturdayTF = new javax.swing.JTextField();
        thursdayTF = new javax.swing.JTextField();
        saturdayLBL = new javax.swing.JLabel();
        tuesdayLBL = new javax.swing.JLabel();
        fridayLBL = new javax.swing.JLabel();
        ascfemaleRB = new javax.swing.JRadioButton();
        ascgenderLBL = new javax.swing.JLabel();
        ascmaleRB = new javax.swing.JRadioButton();
        asctitleLBL = new javax.swing.JLabel();
        ascsubtitleLBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ascmainpageBTN = new javax.swing.JButton();
        ascreturnBTN = new javax.swing.JButton();
        asccalculateBTN = new javax.swing.JButton();
        ascageLBL = new javax.swing.JLabel();
        ascageTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 167, 186));

        sundayLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        sundayLBL.setText("Sunday");

        mondayLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        mondayLBL.setText("Monday");

        thursdayLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        thursdayLBL.setText("Thursday");

        wednesdayLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        wednesdayLBL.setText("Wednesday");

        saturdayLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        saturdayLBL.setText("Saturday");

        tuesdayLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tuesdayLBL.setText("Tuesday");

        fridayLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        fridayLBL.setText("Friday");

        ascfemaleRB.setBackground(new java.awt.Color(186, 167, 186));
        buttonGroup1.add(ascfemaleRB);
        ascfemaleRB.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ascfemaleRB.setText("Female");

        ascgenderLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ascgenderLBL.setText("Gender");

        ascmaleRB.setBackground(new java.awt.Color(186, 167, 186));
        buttonGroup1.add(ascmaleRB);
        ascmaleRB.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ascmaleRB.setText("Male");

        asctitleLBL.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        asctitleLBL.setText("Average Sleep Calculator");

        ascsubtitleLBL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ascsubtitleLBL.setText("Insert your amount of hours of sleep night-by-night.");

        ascmainpageBTN.setText("RETURN  TO MAIN PAGE");

        ascreturnBTN.setText("RETURN TO SLEEP TRACKER PAGE");
        ascreturnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascreturnBTNActionPerformed(evt);
            }
        });

        asccalculateBTN.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        asccalculateBTN.setText("CALCULATE!");

        ascageLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ascageLBL.setText("Age:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ascsubtitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(asctitleLBL)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(mondayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(tuesdayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(wednesdayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(thursdayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(fridayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(saturdayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sundayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(ascreturnBTN)
                        .addGap(45, 45, 45)
                        .addComponent(ascmainpageBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ascageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(asccalculateBTN)
                                .addGap(32, 32, 32))
                            .addComponent(ascageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(mondayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tuesdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(wednesdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(thursdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(fridayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(saturdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(sundayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(ascgenderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ascmaleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ascfemaleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(asctitleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ascsubtitleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wednesdayLBL)
                    .addComponent(tuesdayLBL)
                    .addComponent(mondayLBL)
                    .addComponent(thursdayLBL)
                    .addComponent(fridayLBL)
                    .addComponent(saturdayLBL)
                    .addComponent(sundayLBL))
                .addGap(72, 72, 72)
                .addComponent(ascageLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asccalculateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ascageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ascreturnBTN)
                    .addComponent(ascmainpageBTN))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mondayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tuesdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wednesdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thursdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fridayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saturdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sundayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ascgenderLBL)
                        .addComponent(ascfemaleRB))
                    .addGap(18, 18, 18)
                    .addComponent(ascmaleRB)
                    .addContainerGap(106, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ascreturnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascreturnBTNActionPerformed
        // TODO add your handling code here:
        SleepTrackerMainPageGUI stmp = new SleepTrackerMainPageGUI();
        stmp.setVisible(true);
        dispose();

    }//GEN-LAST:event_ascreturnBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SleepCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SleepCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SleepCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SleepCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SleepCalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ascageLBL;
    private javax.swing.JTextField ascageTF;
    private javax.swing.JButton asccalculateBTN;
    private javax.swing.JRadioButton ascfemaleRB;
    private javax.swing.JLabel ascgenderLBL;
    private javax.swing.JButton ascmainpageBTN;
    private javax.swing.JRadioButton ascmaleRB;
    private javax.swing.JButton ascreturnBTN;
    private javax.swing.JLabel ascsubtitleLBL;
    private javax.swing.JLabel asctitleLBL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fridayLBL;
    private javax.swing.JTextField fridayTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mondayLBL;
    private javax.swing.JTextField mondayTF;
    private javax.swing.JLabel saturdayLBL;
    private javax.swing.JTextField saturdayTF;
    private javax.swing.JLabel sundayLBL;
    private javax.swing.JTextField sundayTF;
    private javax.swing.JLabel thursdayLBL;
    private javax.swing.JTextField thursdayTF;
    private javax.swing.JLabel tuesdayLBL;
    private javax.swing.JTextField tuesdayTF;
    private javax.swing.JLabel wednesdayLBL;
    private javax.swing.JTextField wednesdayTF;
    // End of variables declaration//GEN-END:variables
}
