/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sleeptrackerapp;

/**
 *
 * @author muril
 */
public class SleepTrackerMainPageGUI extends javax.swing.JFrame {

    /**
     * Creates new form SleepTrackerMainPage
     */
    public SleepTrackerMainPageGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sleepcalculatorBTN = new javax.swing.JButton();
        idealbedtimeBTN = new javax.swing.JButton();
        sleeptrackertitleLBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        subtitleLBL = new javax.swing.JLabel();
        scdescriptionLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sleepcalculatorTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        idealbedtimeTA = new javax.swing.JTextArea();
        mainpageBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(186, 167, 186));

        sleepcalculatorBTN.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        sleepcalculatorBTN.setText("Sleep Calculator");
        sleepcalculatorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepcalculatorBTNActionPerformed(evt);
            }
        });

        idealbedtimeBTN.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        idealbedtimeBTN.setText("Ideal Bed Time");
        idealbedtimeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idealbedtimeBTNActionPerformed(evt);
            }
        });

        sleeptrackertitleLBL.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        sleeptrackertitleLBL.setText("Sleep Tracker");

        subtitleLBL.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        subtitleLBL.setText("Improve your quality of sleep.");

        scdescriptionLBL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        sleepcalculatorTA.setEditable(false);
        sleepcalculatorTA.setBackground(new java.awt.Color(186, 167, 186));
        sleepcalculatorTA.setColumns(20);
        sleepcalculatorTA.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        sleepcalculatorTA.setLineWrap(true);
        sleepcalculatorTA.setRows(5);
        sleepcalculatorTA.setText("Calculating your average sleep hours can help you understand your\nsleep patterns and improve your overall well-being.");
        sleepcalculatorTA.setWrapStyleWord(true);
        jScrollPane1.setViewportView(sleepcalculatorTA);

        idealbedtimeTA.setEditable(false);
        idealbedtimeTA.setBackground(new java.awt.Color(186, 167, 186));
        idealbedtimeTA.setColumns(20);
        idealbedtimeTA.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idealbedtimeTA.setLineWrap(true);
        idealbedtimeTA.setRows(5);
        idealbedtimeTA.setText("Calculate your ideal bed time according to your age and gender.");
        jScrollPane3.setViewportView(idealbedtimeTA);

        mainpageBTN.setText("RETURN TO MAIN PAGE");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\muril\\OneDrive\\Área de Trabalho\\College\\Semester 3\\Object Oriented Programming - Thornbury E\\CA1\\SleepTrackerApp\\Images\\sleep1.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\muril\\OneDrive\\Área de Trabalho\\College\\Semester 3\\Object Oriented Programming - Thornbury E\\CA1\\SleepTrackerApp\\Images\\sleep2.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sleepcalculatorBTN)
                                .addGap(217, 217, 217)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(idealbedtimeBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(mainpageBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(subtitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sleeptrackertitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(453, 453, 453)
                            .addComponent(scdescriptionLBL)))
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sleepcalculatorBTN)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idealbedtimeBTN)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainpageBTN)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sleeptrackertitleLBL)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(subtitleLBL)
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(81, 81, 81)
                    .addComponent(scdescriptionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sleepcalculatorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepcalculatorBTNActionPerformed
        // TODO add your handling code here:
        SleepCalculatorGUI sc = new SleepCalculatorGUI();
        sc.setVisible(true);
        dispose();       
    }//GEN-LAST:event_sleepcalculatorBTNActionPerformed

    private void idealbedtimeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idealbedtimeBTNActionPerformed
        // TODO add your handling code here:
        IdealBedTimeGUI ibt = new IdealBedTimeGUI();
        ibt.setVisible(true);
        dispose(); 
        
    }//GEN-LAST:event_idealbedtimeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SleepTrackerMainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SleepTrackerMainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SleepTrackerMainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SleepTrackerMainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SleepTrackerMainPageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton idealbedtimeBTN;
    private javax.swing.JTextArea idealbedtimeTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mainpageBTN;
    private javax.swing.JLabel scdescriptionLBL;
    private javax.swing.JButton sleepcalculatorBTN;
    private javax.swing.JTextArea sleepcalculatorTA;
    private javax.swing.JLabel sleeptrackertitleLBL;
    private javax.swing.JLabel subtitleLBL;
    // End of variables declaration//GEN-END:variables
}
